apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-erp-dev

resources:
  - ../base

namePrefix: dev-
nameSuffix: -dev

commonLabels:
  environment: development

replicas:
  - name: ai-erp-api
    count: 1
  - name: ai-erp-web
    count: 1
  - name: ai-erp-worker
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: ai-erp-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development
      - op: replace
        path: /data/DB_NAME
        value: ai_erp_development
      - op: replace
        path: /data/API_BASE_URL
        value: https://dev-api.erp-domain.com
      - op: replace
        path: /data/ENABLE_AI_COPILOT
        value: "true"

  - target:
      kind: Ingress
      name: ai-erp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-api.erp-domain.com
      - op: replace
        path: /spec/rules/1/host
        value: dev-admin.erp-domain.com
      - op: replace
        path: /spec/rules/2/host
        value: dev-store.erp-domain.com
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - dev-api.erp-domain.com
          - dev-admin.erp-domain.com
          - dev-store.erp-domain.com
      - op: replace
        path: /spec/tls/0/secretName
        value: dev-ai-erp-tls

  - target:
      kind: HorizontalPodAutoscaler
      name: ai-erp-api-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

images:
  - name: ghcr.io/nyeinpyaesone-ui/ai-erp-api
    newTag: develop
  - name: ghcr.io/nyeinpyaesone-ui/ai-erp-web
    newTag: develop
  - name: ghcr.io/nyeinpyaesone-ui/ai-erp-worker
    newTag: develop

