apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-erp

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - network-policy.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: ai-erp
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/nyeinpyaesone-ui/ai-erp-api
    newTag: latest
  - name: ghcr.io/nyeinpyaesone-ui/ai-erp-web
    newTag: latest
  - name: ghcr.io/nyeinpyaesone-ui/ai-erp-worker
    newTag: latest

