apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erp_solution

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - rbac.yaml
  - network-policy.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - worker-deployment.yaml
  - ingress.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: erp_solution
  app.kubernetes.io/managed-by: kustomize

images:
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-api
    newTag: latest
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-web
    newTag: latest
  - name: ghcr.io/nyeinpyaesone-ui/erp_solution-worker
    newTag: latest

