apiVersion: v1
kind: Namespace
metadata:
  name: erp_solution
  labels:
    app.kubernetes.io/name: erp_solution
    app.kubernetes.io/part-of: erp_solution-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: erp_solution-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: erp_solution-system

